name: Track GitHub Profile Views (Go + Python)

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  fetch_and_log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Run Go fetch script
        run: go run scripts/fetch_views.go

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: pip install -r scripts/requirements.txt

      - name: Run Python plot script
        run: python scripts/plot_views.py

      - name: Commit and push updates
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add assets/views.csv assets/views.png
          git commit -m "Update view log and plot" || echo "No changes"
          git push
